### ISSUE TITLE
Twitterbot user agent check is breaking link previews on iOS

### ISSUE THREAD

**Issue by kirb** [hachyderm/community#212]
### Please describe the issue you are seeing.

Hi team, thank you for responding so quickly to the incredibly strange Mastodon link ban.

As a side-effect of returning a different response to Twitterbot user agents, Hachyderm is no longer displaying link previews on iOS. This results in apps that use iOS’s link preview functionality, most notably Messages, displaying any Hachyderm link as a 31 byte “file”:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/773309/208247530-77caf63a-4f4c-4a35-a174-52d86bb31036.png">

That matches up with the `move along, nothing to see here` response I get if I do `curl https://hachyderm.io/ -A 'Twitterbot/1.0'`.

iOS fetches link previews with the following very strange user agent:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0

I believe all version numbers in this are hardcoded (I tested against my own server from iOS 16.2, not OS X 10.11.1!) so you should be able to rely on checking for this exact string or any specific detail of it. However, I’d still be concerned about other legitimate link preview fetchers that pretend to be Twitterbot. Is there possibly a safer way this could be implemented, e.g. by limiting it to known Twitter IP ranges instead?

### How long have you noticed this issue?

As of yesterday

### What geographic region are you accessing Hachyderm from?

Australia

**Comment by quintessence** [comment]
👋 Mod here. I'm wondering if this is actually related to Issue #213 which we're working on right now. After we resolve the issue I'll respond here. Please let us know if the issue persists past that :)

**Comment by quintessence** [comment]
This issue should be resolved with the cache fixes. Please open a new issue if it persists :D

**Comment by kirb** [comment]
Still an issue, I think this got mixed up with the cache problems that were going on at the same time, but it's a different concern entirely.

You can test this directly with:

```
$ curl -i https://hachyderm.io/ -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0'
HTTP/1.1 200 OK
Server: nginx/1.22.1
Date: Sun, 18 Dec 2022 04:02:25 GMT
Content-Type: application/octet-stream
Content-Length: 31
Connection: keep-alive
X-Host: cdn-fremont-1

move along, nothing to see here
```

The 31 byte "file" iOS displays the link as lines up with the Content-Length and Content-Type the server is returning.

Should I refile the issue, or can you reopen this?

**Comment by quintessence** [comment]
Re-Opening and Re-Reading :)

**Comment by timdmackey** [comment]
Possible duplicates: #218 #217

**Comment by quintessence** [comment]
Update: Thank you for your patience! Our infra team is coming back from the holidays next week and we're reviewing these open tickets :) 

We were also able to reproduce this issue in the Discord, link to chat for reference:

https://discord.com/channels/858148454953254943/968553429800714260/1058370476231110677

(This is more for anyone in the Nivenly Discord, link to join on our About page if not)

**Comment by OneJaeAtATime** [comment]
Thank you. Came to post about it.

**Comment by hazelweakly** [comment]
ohhhhh so _that's_ what's been causing this, omg.

non-local side effects are *wild*

That said, I know how to fix it, and I will do so shortly :)

**Comment by hazelweakly** [comment]
This should be fixed now! I've removed the Twitterbot handling (which we had in place temporarily to try and get around twitter banning all links about mastodon)

I tested `curl https://hachyderm.io/ -A 'Twitterbot/1.0'` and that works. I don't have an iOS device to test the messages thing, but given that the curl works, it _should_ be good to go.
