### ISSUE TITLE
journa.host still silenced?

### ISSUE THREAD

**Issue by wlonkly** [hachyderm/community#264]
### What domain(s) need to be added or removed from our blocklist?

I know that back in #211 we unsilenced journa.host, but earlier today I noticed that [mathewi@journa.host](https://hachyderm.io/@mathewi@journa.host/) still shows "This profile has been hidden by the moderators of hachyderm.io", as does [the admin account there](https://hachyderm.io/@info@journa.host). 

I don't see it in the blocklist on about/, but not sure what's going on -- if we intended to refederate and unsilence in #211 maybe something didn't work?

**Comment by freiheit** [comment]
In the moderation/admin interface, I don't see any Silencing/Limiting on the domain itself:
![image](https://user-images.githubusercontent.com/19813/212568136-671966a8-29d4-4f3e-8ab2-c6e709c22edd.png)

However, spot-checking a few of the most popular accounts on journa.host, I see _those_ as "Limited"; same as your first example. And no notes or mod action records on those accounts, so not something that was actually done by a moderator for those individual accounts.

To me, it looks like there's some kind of technical problem making the "Limit" sticky?

**Comment by quintessence** [comment]
👋 It looks like I have a comment on 211 that it looks like it was taking "a minute" for the un-silence to propagate. I just looked internally now and based on some quick napkin math (due to pagination) that when journa.host was silenced it limited all active accounts at that time, but when it was un-silenced it didn't reverse that action. Basically, to truly fix it we'd need to audit about 1500 accounts to manually un-silence them. 

This is going to be backlogged for a minute as we'll need to figure out how to balance that work.

**Comment by freiheit** [comment]
Is this the same as the bug reported in mastodon/mastodon#21414?

**Comment by quintessence** [comment]
Looks like it

**Comment by quintessence** [comment]
Update on this: the next release of Mastodon should fix this issue. We'll know at that time if we need to go through manually fix the journa.host accounts and/or they will resolve as part of the update. I've moved this into our internal moderation queue and I'm closing to close this ticket. For the internal ticket, I'll either resolve with the update (if it resolves at that time) or we'll divvy up the labor and figure fixing the accounts one by one (which make take some time so please be patient with us :) )

Thank you all for your patience :)

**Comment by Aranjedeath** [comment]
Sorry to post on a closed issue -- is "the next version of Mastodon" a 4.1.x or a potentially forthcoming 4.2 ? Still seeing this issue (perhaps I am unlucky and the account I am checking currently had a manual action taken against it)

**Comment by hachyderm-admin** [comment]
No worries and sorry about that! We actually ended up having a report on #448 about qoto that ended up being the same issue: it looks like the tooling didn't catch all the accounts, only some. We're going through them manually in batches, which basically means that instead of seeing a dramatic "aha" it'll be iterative as we get further and further down the list. Since the nature of the issue means that which accounts were impacted by server level action vs individual account action, we're re-auditing / checking our audit trails on the individual accounts so we don't unblock an account we blocked with cause.

If you have a list of the accounts you'd like to follow, can you please either comment them here or email them to us? We can prioritize reviewing those accounts like we've done with some of the qoto accounts.

**Comment by hachyderm-admin** [comment]
The reason journa.host wasn't caught sooner is that many accounts are successfully federating, so we looked deeper into the issue as part of the qoto ticket. Again, apologies!

**Comment by Aranjedeath** [comment]
Ah! Thank you!!!

No, I will let you work as you will. No need to intervene. 

It's one of the old style, where the profile appears muted. I have seen the individual account blocks which prevent me from following entirely, and this is not that.

Thank you for doing these checks :)

**Comment by soupglasses** [comment]
We now have scripts written and ready to help fix this for all affected accounts. So this will be properly fixed in the next scheduled infrastructure meeting. Gonna be nice to get this longstanding issue fixed for good (hopefully).
